[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = 'go'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_ft = 'go'


[[plugins]]
repo = 'landaire/deoplete-swift'
on_ft = 'swift'
hook_source = '''
let g:deoplete#sources#swift#daemon_autostart = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


# Rubyのメソッドの定義元にジャンプ
[[plugins]]
repo = 'szw/vim-tags'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-dispatch'
on_ft = 'ruby'

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = 'ruby'
hook_add = '''
let g:rspec_command = 'Dispatch rspec {spec}'
'''

# Swift
[[plugins]]
repo = 'kballard/vim-swift'
on_i = 1
on_ft = ['swift']

[[plugins]]
repo = 'keith/swift.vim'
on_i = 1
on_ft = ['swift']


[[plugins]]

[[plugins]]
repo='aklt/plantuml-syntax'
on_i= 1
on_ft = 'uml'

repo = 'iamcco/markdown-preview.nvim'
on_ft = 'markdown'
build = 'cd app & yarn install'

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'

[[plugins]]
repo = 'uarun/vim-protobuf'
on_ft = 'proto'
