[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'ujihisa/unite-locate'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'violetyk/cake.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/ZenCoding.vim'

[[plugins]]
repo = 'vim-scripts/ref.vim'

[[plugins]]
repo = 'vim-scripts/The-NERD-tree'

[[plugins]]
repo = 'vim-scripts/The-NERD-Commenter'

[[plugins]]
repo = 'vim-scripts/fugitive.vim'

[[plugins]]
repo = 'thinca/vim-localrc'

[[plugins]]
repo = 'motemen/hatena-vim'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattn/unite-advent_calendar'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'vim-scripts/JavaScript-syntax'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'tell-k/vim-browsereload-mac'

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'sbl/scvim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'

[[plugins]]
repo = 'ujihisa/neco-ghc'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'kana/vim-filetype-haskell'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'dag/vim2hs'

[[plugins]]
repo = 'felixge/vim-nodejs-errorformat'

[[plugins]]
repo = 'geekjuice/vim-mocha'

[[plugins]]
repo = 'rickard/project.vim'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = '''
let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'bpowell/vim-android'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'sjl/gundo.vim'


[[plugins]]
repo = 'Shougo/neomru.vim'


[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'whatyouhide/vim-gotham'

[[plugins]]
repo = 'ajh17/Spacegray.vim'

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'Keithbsmiley/swift.vim'

[[plugins]]
repo = 'toyamarinyon/vim-swift'


[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'rhysd/rust-doc.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'

[[plugins]]
repo = 'Shougo/neocomplcache-rsense.vim'

[[plugins]]
repo = 'munshkr/vim-tidal'

[[plugins]]
repo = 'vim-utils/vim-man'

[[plugins]]
repo = 'lighttiger2505/gtags.vim'
hook_add = '''
    let g:Gtags_Auto_Map = 0
    let g:Gtags_OpenQuickfixWindow = 1
'''


[[plugins]]
repo = 'ozelentok/denite-gtags'
hook_add = '''
" Prefix key
nmap [denite] <Nop>
map <C-j> [denite]
" Keymap
nmap <silent> [denite]<C-D> :Denite -buffer-name=gtags_completion gtags_completion<cr>
'''


[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 200
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#max_list = 500
'''
on_i = 1
[[plugins]]
repo = 'milch/vim-fastlane'


[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim' 
rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.dotfiles/neovim/plugins/LanguageClient_neovim.vim
'''

[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.dotfiles/neovim/plugins/ale.vim
'''

[[pluings]]
repo = 'dracula/vim'
hook_add = '''
set background=dark
au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

