[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = 'go'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_ft = 'go'


[[plugins]]
repo = 'landaire/deoplete-swift'
on_ft = 'swift'
hook_source = '''
let g:deoplete#sources#swift#daemon_autostart = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


# Rubyのメソッドの定義元にジャンプ
[[plugins]]
repo = 'szw/vim-tags'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-dispatch'
on_ft = 'ruby'

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = 'ruby'
hook_add = '''
let g:rspec_command = 'Dispatch rspec {spec}'
'''

# Swift
[[plugins]]
repo = 'kballard/vim-swift'
on_i = 1
on_ft = ['swift']

[[plugins]]
repo = 'keith/swift.vim'
on_i = 1
on_ft = ['swift']


[[plugins]]
repo='aklt/plantuml-syntax'
on_i= 1
on_ft = 'uml'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = 'markdown'
build = 'cd app & yarn install'
rev = 'dependabot/npm_and_yarn/next-12.1.0'
hook_add = '''
let g:mkdp_browser = 'Safari'
'''

[[plugins]]
repo = 'uarun/vim-protobuf'
on_ft = 'proto'


[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown', 'graphql']


[[plugins]]
repo='hashivim/vim-terraform'
on_ft=['terraform','tf']

