[[plugins]]
repo = 'sebdah/vim-delve'
on_ft = 'go'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_ft = 'go'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'


[[plugins]]
repo = 'landaire/deoplete-swift'
on_ft = 'swift'
hook_source = '''
let g:deoplete#sources#swift#daemon_autostart = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'
hook_add = '''
let g:monster#completion#backend = 'solargraph'
let g:monster#completion#solargraph#backend = "async_solargraph_suggest"
let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

# Rubyのメソッドの定義元にジャンプ
[[plugins]]
repo = 'szw/vim-tags'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-dispatch'
on_ft = 'ruby'

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = 'ruby'
hook_add = '''
let g:rspec_command = 'Dispatch rspec {spec}'
'''

# Swift 
[[plugins]]
repo = 'kballard/vim-swift'
on_i = 1
on_ft = ['swift']

[[plugins]]
repo = 'keith/swift.vim'
on_i = 1
on_ft = ['swift']

[[plugins]]
repo='mitsuse/autocomplete-swift'
on_i = 1
on_ft = ['swift']

repo = 'supercollider/scvim'
on_i = 1
on_ft = 'sc'
hook_source=''''
    let g:sclangTerm="open -a iTerm"
    let g:sclangPipeApp="~/.cache/dein/repos/github.com/supercollider/scvim/bin/start_pipe"
    let g:sclangDispatcher="~/.cache/dein/repos/github.com/supercollider/scvim/bin/sc_dispatcher"
    let g:scFlash = 1
'''


[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_fmt_command = "goimports"
  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
'''
